# Generated by Django 4.1.4 on 2022-12-13 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0009_alter_horario_socio'),
        ('agenda', '0003_agenda_generadoauto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.CharField(max_length=50, verbose_name='Ejercicio')),
                ('foto', models.FileField(upload_to='documentos/ejercicios/fotos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='Foto')),
                ('video', models.FileField(upload_to='documentos/ejercicios/videos/', validators=[django.core.validators.FileExtensionValidator(['avi', 'mp4'])], verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rutina_agenda', to='agenda.agenda', verbose_name='Agenda')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rutina_socio', to='socios.socio', verbose_name='Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('repeticiones', models.IntegerField(verbose_name='Repeticiones')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='elemento_ejercicio', to='rutinas.ejercicio', verbose_name='Ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenedor', models.CharField(max_length=50, verbose_name='Serie')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contenedor_rutina', to='rutinas.rutina', verbose_name='Rutina')),
            ],
        ),
    ]
