# Generated by Django 4.1.4 on 2022-12-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='ejercicio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='elemento_ejercicio', to='rutinas.ejercicio', verbose_name='Ejercicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elemento',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='elemento_contenedor', to='rutinas.contenedor', verbose_name='Contenedor'),
        ),
    ]
