# Generated by Django 4.1.4 on 2022-12-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0009_alter_horario_socio'),
        ('agenda', '0003_agenda_generadoauto'),
        ('rutinas', '0002_elemento_ejercicio_alter_elemento_contenedor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rutina',
            unique_together={('socio', 'agenda')},
        ),
    ]
