# Generated by Django 4.1.4 on 2022-12-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0009_alter_horario_socio'),
        ('agenda', '0003_agenda_generadoauto'),
        ('rutinas', '0003_alter_rutina_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenedor_rutina', to='rutinas.rutina', verbose_name='Rutina'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemento_contenedor', to='rutinas.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_agenda', to='agenda.agenda', verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutina_socio', to='socios.socio', verbose_name='Socio'),
        ),
    ]
