# Generated by Django 4.1.4 on 2022-12-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_alter_contenedor_rutina_alter_elemento_contenedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='peso',
            field=models.FloatField(default=0, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='elemento',
            name='repeticiones',
            field=models.IntegerField(default=0, verbose_name='Repeticiones'),
        ),
    ]
