# Generated by Django 4.1.4 on 2022-12-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_alter_elemento_peso_alter_elemento_repeticiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenedor_modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenedor', models.CharField(max_length=50, verbose_name='Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina_modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento_modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(default=0, verbose_name='Peso')),
                ('repeticiones', models.IntegerField(default=0, verbose_name='Repeticiones')),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemento_Contenedor_modelo', to='rutinas.contenedor_modelo', verbose_name='Contenedor')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ejercicio_elemento_modelo', to='rutinas.ejercicio', verbose_name='Ejercicio')),
            ],
        ),
        migrations.AddField(
            model_name='contenedor_modelo',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenedor_rutina_modelo', to='rutinas.rutina_modelo', verbose_name='Rutina'),
        ),
    ]
