# Generated by Django 4.1.3 on 2022-11-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('estado', models.CharField(choices=[('PAGO', 'Pago'), ('IMPAGO', 'Impago')], max_length=50, verbose_name='Estado')),
                ('monto', models.FloatField(verbose_name='Monto')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='socio_pago', to='socios.socio', verbose_name='Socio')),
            ],
        ),
    ]
