# Generated by Django 4.1.3 on 2022-11-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='concepto',
            field=models.CharField(default='', max_length=50, verbose_name='Concepto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='fechapago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
    ]
