# Generated by Django 4.1.3 on 2022-12-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_socio_dni'),
        ('pagos', '0002_pago_concepto_pago_fechapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='socio_agenda', to='socios.socio', verbose_name='Socio'),
        ),
    ]
