# Generated by Django 4.1.3 on 2022-11-29 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('documento', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'doc', 'docx', 'xlsx'])], verbose_name='Documento')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='socio_documento', to='socios.socio', verbose_name='Socio')),
            ],
        ),
    ]
