# Generated by Django 4.1.3 on 2022-12-06 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'doc', 'docx', 'xlsx', 'jpeg'])], verbose_name='Documento'),
        ),
    ]
