# Generated by Django 4.1.3 on 2022-12-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_socio_dni'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('socio', 'fecha', 'hora')},
        ),
    ]
