# Generated by Django 4.1.3 on 2022-12-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_agenda_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='generadoAuto',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Generado Automaticamente'),
        ),
    ]
