# Generated by Django 4.1.3 on 2022-11-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50, verbose_name='Concepto')),
                ('monto', models.FloatField(verbose_name='Monto')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('fechanacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=50, verbose_name='Estado')),
                ('obsevaciones', models.TextField(verbose_name='Observaciones')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuota_socio', to='socios.cuota')),
            ],
        ),
    ]
