# Generated by Django 4.1.3 on 2022-12-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_socio_direccion_alter_socio_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
    ]
