# Generated by Django 4.1.3 on 2022-12-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='domingo',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Domingo'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='jueves',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Jueves'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='lunes',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Lunes'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='martes',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Martes'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='miercoles',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Miercoles'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='sabado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Sabado'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='viernes',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Viernes'),
        ),
    ]
