# Generated by Django 4.1.3 on 2022-12-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_alter_horario_domingo_alter_horario_jueves_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='virnesHorario',
            new_name='viernesHorario',
        ),
    ]
